M48
; DRILL file {KiCad 7.0.9} date Tue Jan  2 09:41:12 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-02T09:41:12+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X3.5485Y-3.5616
X3.5485Y-3.7584
T2
X2.2057Y-3.5109
X2.2057Y-3.6291
T3
X2.2441Y-3.189
X2.2441Y-4.2126
X3.622Y-3.189
X3.622Y-4.2126
T0
M30
